export const API_BASE_URL =
  'https://sherlock-homie.cognitiveservices.azure.com/';
export const API_KEY = '7b8131f86ba64d68bcc5fe806d44974c';
export const PERSON_GRP_ID = 'group_id1';
export const PERSON_GRP_NAME = 'group_name1';
export const PERSON_DETAIL_API = '/face/v1.0/persongroups/';
export const DETECT_API = '/face/v1.0/detect';
export const IDENTIFY_API = '/face/v1.0/identify';
export const TRAIN_API = 'face/v1.0/persongroups/';
export const BACKEND_API_BASE_URL = 'https://sherlock-homie-api.herokuapp.com/';
export const GET_CONTACT_API = 'Contact';
export const REPORT_API = 'AddSuspect';
export const LOGIN_API = 'User/Login';
export const SUSPECT_API = 'Suspects';
export const SUSPECTDATA_API = '/Suspects/Location';
export const LOCATION = 'Vijaya Forum Mall, Chennai';
export const APP_NAME = 'Sherlock-Homie';
export const SUCCESS_MESSAGE = 'Reported the suspect.';
export const NETWORK_ERROR = 'Network error. Check Internet connections.';
